//@type-next
import { InferGetServerSidePropsType } from "next";
//next
import Head from "next/head";
import { Header } from "../../components/header";
//hook
import { useContextHook } from "../../context/Context";
//types
import { Data } from "../../components/home";

export const getServerSideProps = async () => {
  const res = await fetch("https://cdn.mallconomy.com/testcase/actions.json");
  const data: Data[] = await res.json();

  return {
    props: {
      data,
    },
  };
};

export default function Points({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { completedItem } = useContextHook();
  return (
    <div>
      <Head>
        <title>My Points || Enes Unluer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="point-container">
        <h3>Completed actions</h3>
        {data
          ?.filter(({ id }) => completedItem.includes(id))
          .map(({ title, point, id }) => (
            <div key={id} className="point--item">
              <p className="point--title">{title}</p>
              <p className="point--point">{`+${point}`}</p>
            </div>
          ))}
      </div>
    </div>
  );
}
