//@type-next
import { InferGetServerSidePropsType } from "next";
//next
import Head from "next/head";
//component
import { Data, Home } from "../components/home";
import { Intro } from "../components/intro";

export const getServerSideProps = async () => {
  const res = await fetch("https://cdn.mallconomy.com/testcase/actions.json");
  const data: Data[] = await res.json();

  return {
    props: {
      data,
    },
  };
};

export default function HomePage({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home items={data} />
      </main>
      {/* <main>
        <Intro />
      </main> */}
      <footer></footer>
    </div>
  );
}
